version: '3.9'
services:
    bs-rabbitmq:
        container_name: bsrabbitmq
        image: 'rabbitmq:3.9-management'
        network_mode: "host"
        healthcheck:
          test: rabbitmq-diagnostics check_port_connectivity
          interval: 1s
          timeout: 3s
          retries: 30
        restart: unless-stopped
        logging:
            options:
                max-size: 4m
                
    bs-status-api:
        container_name: bsstatus
        image: ghcr.io/beattogether/beat-together-status-api:sha-64c04e8
        depends_on:
          bs-rabbitmq:
            condition: service_healthy
        ports:
           - '23280:23280'
        network_mode: "host"
        volumes:
          - '${STATUS_CONFIG_FILE}:/app/appsettings.Production.json'
        restart: unless-stopped
        logging:
            options:
                max-size: 4m
    
    bs-master-server:
        container_name: bsmaster
        image: ghcr.io/beattogether/beat-together-master-server:master
        depends_on:
          bs-rabbitmq:
              condition: service_healthy
        ports:
           - '2328:2328'
        network_mode: "host"
        volumes:
          - '${MASTER_CONFIG_FILE}:/app/appsettings.Production.json'
        restart: unless-stopped
        logging:
            options:
                max-size: 4m
    
    bs-dedicated-server:
        container_name: bsdedicated
        image: ghcr.io/beattogether/beat-together-dedicated-server:master
        depends_on:
          bs-rabbitmq:
              condition: service_healthy
        ports:
            - '30000-30500:30000-30500'
        network_mode: "host"
        volumes:
          - '${DEDICATED_CONFIG_FILE}:/app/appsettings.Production.json'
        restart: unless-stopped
        logging:
            options:
                max-size: 4m
